### ISSUE TITLE
Unix MBOX files are not delimited by ".", they are delimited by "From ..."

### ISSUE THREAD

**Issue by jstedfast** [HiraokaHyperTools/LEML#1]
https://github.com/HiraokaHyperTools/LEML/blob/ed409fc4d011ffbc0d0722053ca5dcc4c45f720f/LEML.cs#L585

POP3 and SMTP use "." on a line by itself to terminate the message stream, but that is not considered the MBOX format.

The MBOX format uses lines that start with `"From "` (From + Space). Often they will have a username followed by a timestamp, but not always.

Hope that helps.

**Comment by kenjiuno** [comment]
Hi @jstedfast 
Thanks for advice!
I have confirmed that you are right.
`UnixMboxReader` reads `(Enter).(Enter)` format, not MBOX.
I'll fix it in my free time, thanks!

**Comment by jstedfast** [comment]
You're welcome :-)
